name: new_mac_test
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=3.1.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  google_maps_flutter: ^2.5.0
  http: ^0.13.3
  geolocator: ^10.1.0
  permission_handler: ^11.0.0
  custom_marker: ^1.0.0
  cached_network_image: ^3.3.0
  flutter_custom_clippers: ^2.1.0
  supabase_flutter: ^1.10.25
  mime: ^1.0.4
  uuid: ^4.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
